global:
  scrape_interval: 5s

rule_files:
  - "/etc/prometheus/rules/*.yml"
  # - "rules/alerting-rules.yml"
  # - "rules/recording-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8222' ]
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'  # Endpoint của Spring Boot
    static_configs:
      - targets: ['host.docker.internal:8761']  # 'eureka-server:8761'
  - job_name: 'user-service'  # Thêm cho từng service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'vehicle-service'  # Thêm cho từng service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'verification-service'  # Thêm cho từng service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
  - job_name: 'wallet-service'  # Thêm cho từng service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
  - job_name: 'media-service'  # Thêm cho từng service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
  - job_name: 'market-service'  # Thêm cho từng service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']
  - job_name: 'transaction-service'  # Thêm cho từng service
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']
