eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
name:
  value: carbon_credit_marketplace
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0